apiVersion: v1
kind: Service
metadata:
  name: cloud-monitoring-svc
spec:
  selector:
    app: cloud-monitoring-app
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: LoadBalancer

